name: List Directories

on:
  push:
    branches:
      - main

jobs:
  list-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Aligned with 'name'

      - name: List all directories
        run: |                    # Aligned with 'name'
          find . -type d
          ls -la
          mkdir olum
          ls -la